export const movies = [
  { id: 1, title: "Inception", image: "https://picsum.photos/200?1", description: "Sci-fi thriller." },
  { id: 2, title: "Interstellar", image: "https://picsum.photos/200?2", description: "Space adventure." },
  { id: 3, title: "Avatar", image: "https://picsum.photos/200?3", description: "Epic fantasy." },
  { id: 4, title: "Joker", image: "https://picsum.photos/200?4", description: "Psychological drama." },
  { id: 5, title: "Titanic", image: "https://picsum.photos/200?5", description: "Romantic tragedy." },
  { id: 6, title: "Matrix", image: "https://picsum.photos/200?6", description: "Action sci-fi." },
  { id: 7, title: "Gladiator", image: "https://picsum.photos/200?7", description: "Historical epic." },
  { id: 8, title: "Frozen", image: "https://picsum.photos/200?8", description: "Animated musical." },
  { id: 9, title: "Batman", image: "https://picsum.photos/200?9", description: "Superhero film." },
  { id: 10, title: "Spider-Man", image: "https://picsum.photos/200?10", description: "Marvel hero." },
  { id: 11, title: "Dune", image: "https://picsum.photos/200?11", description: "Sci-fi epic." },
  { id: 12, title: "Coco", image: "https://picsum.photos/200?12", description: "Family drama." },
  { id: 13, title: "Up", image: "https://picsum.photos/200?13", description: "Adventure film." },
  { id: 14, title: "Shrek", image: "https://picsum.photos/200?14", description: "Comedy fantasy." },
  { id: 15, title: "Thor", image: "https://picsum.photos/200?15", description: "Marvel action." },
  { id: 16, title: "Iron Man", image: "https://picsum.photos/200?16", description: "Superhero origin." },
  { id: 17, title: "Hulk", image: "https://picsum.photos/200?17", description: "Marvel hero." },
  { id: 18, title: "Captain America", image: "https://picsum.photos/200?18", description: "Superhero origin." },
  { id: 19, title: "Black Widow", image: "https://picsum.photos/200?19", description: "Marvel hero." },
  { id: 20, title: "Hawkeye", image: "https://picsum.photos/200?20", description: "Marvel hero." },
];
